//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Table
    {
        public decimal CustomerNo { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Birth { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Date { get; set; }
    }
}
