//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depotist_Table
    {
        public int SNO { get; set; }
        public Nullable<decimal> CustomerNo { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public string Mode { get; set; }
        public Nullable<decimal> DipositAmout { get; set; }
        public string Date { get; set; }
    }
}
